### ISSUE TITLE
Discussion: New schematics in the block

### ISSUE THREAD

**Issue by GregOnNet** [co-IT/schematics#37]
According to the tweet of Jan-Nicklas Wortmann we can discuss his idea to add some schematics to enhance the productivity even further: https://twitter.com/niklas_wortmann/status/1125807552560816129

The mentioned schematics should:

- [ ] scaffold custom form-validators
- [ ] scaffold custom rxjs operators
- [ ] scaffold a custom route
- [ ] scaffold a reactive form

**Comment by GregOnNet** [comment]
## custom form-validators

### Pros

I think it is a good idea to have a generator for the mentioned snippets because it helps setting up mechanisms that are not used that often (form-validators or rxjs operators).
This will save the developer some time to look up the needed boiler plate code.

### Cons

Maybe an IDE-code-snippet is the better tool for this requirement.
- Code will be generated quickly
- Developer can add the validator right inside the component or to an own file

In the end, I think a simple snippet fits better here.

**Comment by JWO719** [comment]
Thanks for picking this up. The listed statements are just some examples I came up with first. 
Personally I think schematics are quite a good fit for that, because it's IDE-agnostic and well known within the angular community. Additionally it offers testability, not sure how this looks for IDE-code-snippets. Also depending on the use case it could include multiple files, e.g. a custom form validator depending on the implementation might be spreaded across multiple files. AFAIK VSCode snippets are used just in a dedicated single file

**Comment by JWO719** [comment]
additional things could be:
 - creating a service with a subject
 - creating a lazy loading feature module (with a forRoot & forChild function) 

Happy to support here as much as possible. Just let me know, how I can support.
These are just things I came up with from my daily business routine. I think there are still lots of patterns & best practices which would be quite cool to have a generator for
